### ISSUE TITLE
Publishing to DataONE kills celery

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/gwvolman#108]
```
[2020-07-16 02:59:47,407: INFO/MainProcess] Received task: gwvolman.tasks.publish[5a0a824c-250d-40e1-b076-d98264b2c41c]  
[2020-07-16 02:59:54,301: WARNING/ForkPoolWorker-4] Error uploading file to DataONE urn:uuid:92e109ff-7cc5-4750-9a8e-40ece47131b6 name: InvalidSystemMetadata
errorCode: 400
detailCode: 1180
description: The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.
traceInformation:
  < Accept-Encoding: gzip, deflate
  < Accept: */*
  < Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi0xNzU2LTIxMjgiLCJmdWxsTmFtZSI6IlRob21hcyBUaGVsZW4iLCJpc3N1ZWRBdCI6IjIwMjAtMDctMTZUMDI6NTk6MTQuOTQwKzAwOjAwIiwiY29uc3VtZXJLZXkiOiJ0aGVjb25zdW1lcmtleSIsImV4cCI6MTU5NDkzMzE1NCwidXNlcklkIjoiaHR0cDpcL1wvb3JjaWQub3JnXC8wMDAwLTAwMDItMTc1Ni0yMTI4IiwidHRsIjo2NDgwMCwiaWF0IjoxNTk0ODY4MzU0fQ.KRw1gqwgwpxoQuss6Mwc-9rnoC6Dur1NgJkOpRX4YW-C3ko67QvQinp5nO38Lvzwixy2AExn0eypJ8ktK_jMofY9F-WbTDTQGxw9qzFcdg8M-xLwcvA3YnGJFI9iQVv7F2ux2hOAdqPo486X5prTYUZXCLyB7XBUi6j1BpQ9cIg91us2OoVCF1UEKpeqoecA8YF-Tr-_nbYjKTDhyF5W2E_6uyVrmC3XCe75alXCWn3Pnb0x1v2TJcIgqq8zu-RpwsbWCHfs8_fi2_6Lrf9RSmpl3f_YHpMY_FudJHqMBQR1Y-ilcQIlGrTgWUxxZ9BigZH1sOtPo4rU3k1wXplsyA
  < Charset: utf-8
  < Connection: close
  < Content-Length: 1366
  < Content-Type: multipart/form-data; boundary=5748d4b5c1f2461ab19387522f7b5531
  < Host: dev.nceas.ucsb.edu
  < POST /knb/d1/mn/v2/object HTTP/1.1
  < User-Agent: safari
  
  
  
  << Request body is not a string-like type >>
  > HTTP/1.1 400 400
  > Date: Thu, 16 Jul 2020 02:59:54 GMT
  > Server: Apache/2.4.29 (Ubuntu)
  > X-Frame-Options: SAMEORIGIN
  > X-Frame-Options: sameorigin
  > Vary: User-Agent,Authorization
  > Content-Length: 326
  > Access-Control-Allow-Origin: 
  > Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
  > Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
  > Access-Control-Allow-Credentials: true
  > Connection: close
  > Content-Type: text/xml
  > 
  <?xml version="1.0" encoding="UTF-8"?><error detailCode="1180" errorCode="400" name="InvalidSystemMetadata">
      <description>The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.</description>
  </error>
identifier: <unset>
nodeId: <unset>

[2020-07-16 02:59:54,302: WARNING/ForkPoolWorker-4] Error. Should rollback... name: InvalidSystemMetadata
errorCode: 400
detailCode: 1180
description: The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.
traceInformation:
  < Accept-Encoding: gzip, deflate
  < Accept: */*
  < Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi0xNzU2LTIxMjgiLCJmdWxsTmFtZSI6IlRob21hcyBUaGVsZW4iLCJpc3N1ZWRBdCI6IjIwMjAtMDctMTZUMDI6NTk6MTQuOTQwKzAwOjAwIiwiY29uc3VtZXJLZXkiOiJ0aGVjb25zdW1lcmtleSIsImV4cCI6MTU5NDkzMzE1NCwidXNlcklkIjoiaHR0cDpcL1wvb3JjaWQub3JnXC8wMDAwLTAwMDItMTc1Ni0yMTI4IiwidHRsIjo2NDgwMCwiaWF0IjoxNTk0ODY4MzU0fQ.KRw1gqwgwpxoQuss6Mwc-9rnoC6Dur1NgJkOpRX4YW-C3ko67QvQinp5nO38Lvzwixy2AExn0eypJ8ktK_jMofY9F-WbTDTQGxw9qzFcdg8M-xLwcvA3YnGJFI9iQVv7F2ux2hOAdqPo486X5prTYUZXCLyB7XBUi6j1BpQ9cIg91us2OoVCF1UEKpeqoecA8YF-Tr-_nbYjKTDhyF5W2E_6uyVrmC3XCe75alXCWn3Pnb0x1v2TJcIgqq8zu-RpwsbWCHfs8_fi2_6Lrf9RSmpl3f_YHpMY_FudJHqMBQR1Y-ilcQIlGrTgWUxxZ9BigZH1sOtPo4rU3k1wXplsyA
  < Charset: utf-8
  < Connection: close
  < Content-Length: 1366
  < Content-Type: multipart/form-data; boundary=5748d4b5c1f2461ab19387522f7b5531
  < Host: dev.nceas.ucsb.edu
  < POST /knb/d1/mn/v2/object HTTP/1.1
  < User-Agent: safari
  
  
  
  << Request body is not a string-like type >>
  > HTTP/1.1 400 400
  > Date: Thu, 16 Jul 2020 02:59:54 GMT
  > Server: Apache/2.4.29 (Ubuntu)
  > X-Frame-Options: SAMEORIGIN
  > X-Frame-Options: sameorigin
  > Vary: User-Agent,Authorization
  > Content-Length: 326
  > Access-Control-Allow-Origin: 
  > Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
  > Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
  > Access-Control-Allow-Credentials: true
  > Connection: close
  > Content-Type: text/xml
  > 
  <?xml version="1.0" encoding="UTF-8"?><error detailCode="1180" errorCode="400" name="InvalidSystemMetadata">
      <description>The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.</description>
  </error>
identifier: <unset>
nodeId: <unset>

[2020-07-16 02:59:54,738: WARNING/ForkPoolWorker-4] Instances with absent namespaces can only be reconstructed in-session
[2020-07-16 02:59:55,164: ERROR/ForkPoolWorker-4] <class 'int'>
[2020-07-16 02:59:55,165: ERROR/ForkPoolWorker-4] <class 'pyxb.binding.datatypes.string'>
[2020-07-16 02:59:55,165: ERROR/ForkPoolWorker-4] <class 'pyxb.binding.datatypes.string'>
[2020-07-16 02:59:55,165: ERROR/ForkPoolWorker-4] <class 'str'>
[2020-07-16 02:59:55,165: ERROR/ForkPoolWorker-4] <class 'NoneType'>
[2020-07-16 02:59:55,165: ERROR/ForkPoolWorker-4] <class 'NoneType'>
[2020-07-16 02:59:55,166: ERROR/ForkPoolWorker-4] InvalidSystemMetadata(errorCode="400", detailCode="1180", description="The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.", traceInformation="< Accept-Encoding: gzip, deflate
< Accept: */*
< Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi0xNzU2LTIxMjgiLCJmdWxsTmFtZSI6IlRob21hcyBUaGVsZW4iLCJpc3N1ZWRBdCI6IjIwMjAtMDctMTZUMDI6NTk6MTQuOTQwKzAwOjAwIiwiY29uc3VtZXJLZXkiOiJ0aGVjb25zdW1lcmtleSIsImV4cCI6MTU5NDkzMzE1NCwidXNlcklkIjoiaHR0cDpcL1wvb3JjaWQub3JnXC8wMDAwLTAwMDItMTc1Ni0yMTI4IiwidHRsIjo2NDgwMCwiaWF0IjoxNTk0ODY4MzU0fQ.KRw1gqwgwpxoQuss6Mwc-9rnoC6Dur1NgJkOpRX4YW-C3ko67QvQinp5nO38Lvzwixy2AExn0eypJ8ktK_jMofY9F-WbTDTQGxw9qzFcdg8M-xLwcvA3YnGJFI9iQVv7F2ux2hOAdqPo486X5prTYUZXCLyB7XBUi6j1BpQ9cIg91us2OoVCF1UEKpeqoecA8YF-Tr-_nbYjKTDhyF5W2E_6uyVrmC3XCe75alXCWn3Pnb0x1v2TJcIgqq8zu-RpwsbWCHfs8_fi2_6Lrf9RSmpl3f_YHpMY_FudJHqMBQR1Y-ilcQIlGrTgWUxxZ9BigZH1sOtPo4rU3k1wXplsyA
< Charset: utf-8
< Connection: close
< Content-Length: 1366
< Content-Type: multipart/form-data; boundary=5748d4b5c1f2461ab19387522f7b5531
< Host: dev.nceas.ucsb.edu
< POST /knb/d1/mn/v2/object HTTP/1.1
< User-Agent: safari



<< Request body is not a string-like type >>
> HTTP/1.1 400 400
> Date: Thu, 16 Jul 2020 02:59:54 GMT
> Server: Apache/2.4.29 (Ubuntu)
> X-Frame-Options: SAMEORIGIN
> X-Frame-Options: sameorigin
> Vary: User-Agent,Authorization
> Content-Length: 326
> Access-Control-Allow-Origin: 
> Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
> Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
> Access-Control-Allow-Credentials: true
> Connection: close
> Content-Type: text/xml
> 
<?xml version="1.0" encoding="UTF-8"?><error detailCode="1180" errorCode="400" name="InvalidSystemMetadata">
    <description>The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.</description>
</error>", identifier="None", nodeId="None")
[2020-07-16 02:59:55,166: ERROR/ForkPoolWorker-4] Task gwvolman.tasks.publish[5a0a824c-250d-40e1-b076-d98264b2c41c] raised unexpected: InvalidSystemMetadata(errorCode="400", detailCode="1180", description="The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.", traceInformation="< Accept-Encoding: gzip, deflate
< Accept: */*
< Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi0xNzU2LTIxMjgiLCJmdWxsTmFtZSI6IlRob21hcyBUaGVsZW4iLCJpc3N1ZWRBdCI6IjIwMjAtMDctMTZUMDI6NTk6MTQuOTQwKzAwOjAwIiwiY29uc3VtZXJLZXkiOiJ0aGVjb25zdW1lcmtleSIsImV4cCI6MTU5NDkzMzE1NCwidXNlcklkIjoiaHR0cDpcL1wvb3JjaWQub3JnXC8wMDAwLTAwMDItMTc1Ni0yMTI4IiwidHRsIjo2NDgwMCwiaWF0IjoxNTk0ODY4MzU0fQ.KRw1gqwgwpxoQuss6Mwc-9rnoC6Dur1NgJkOpRX4YW-C3ko67QvQinp5nO38Lvzwixy2AExn0eypJ8ktK_jMofY9F-WbTDTQGxw9qzFcdg8M-xLwcvA3YnGJFI9iQVv7F2ux2hOAdqPo486X5prTYUZXCLyB7XBUi6j1BpQ9cIg91us2OoVCF1UEKpeqoecA8YF-Tr-_nbYjKTDhyF5W2E_6uyVrmC3XCe75alXCWn3Pnb0x1v2TJcIgqq8zu-RpwsbWCHfs8_fi2_6Lrf9RSmpl3f_YHpMY_FudJHqMBQR1Y-ilcQIlGrTgWUxxZ9BigZH1sOtPo4rU3k1wXplsyA
< Charset: utf-8
< Connection: close
< Content-Length: 1366
< Content-Type: multipart/form-data; boundary=5748d4b5c1f2461ab19387522f7b5531
< Host: dev.nceas.ucsb.edu
< POST /knb/d1/mn/v2/object HTTP/1.1
< User-Agent: safari



<< Request body is not a string-like type >>
> HTTP/1.1 400 400
> Date: Thu, 16 Jul 2020 02:59:54 GMT
> Server: Apache/2.4.29 (Ubuntu)
> X-Frame-Options: SAMEORIGIN
> X-Frame-Options: sameorigin
> Vary: User-Agent,Authorization
> Content-Length: 326
> Access-Control-Allow-Origin: 
> Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
> Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
> Access-Control-Allow-Credentials: true
> Connection: close
> Content-Type: text/xml
> 
<?xml version="1.0" encoding="UTF-8"?><error detailCode="1180" errorCode="400" name="InvalidSystemMetadata">
    <description>The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.</description>
</error>", identifier="None", nodeId="None")
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 518, in publish
    provider.publish()
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 241, in publish
    system_metadata=file_meta,
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 375, in _upload_file
    client.create(pid, file_object, system_metadata)
  File "/usr/local/lib/python3.5/dist-packages/d1_client/mnclient.py", line 120, in create
    return self._read_dataone_type_response(response, 'Identifier')
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 261, in _read_dataone_type_response
    self._raise_exception(response)
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 219, in _raise_exception
    self._raise_dataone_exception(response)
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 184, in _raise_dataone_exception
    raise d1_exception
d1_common.types.exceptions.InvalidSystemMetadata: name: InvalidSystemMetadata
errorCode: 400
detailCode: 1180
description: The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.
traceInformation:
  < Accept-Encoding: gzip, deflate
  < Accept: */*
  < Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi0xNzU2LTIxMjgiLCJmdWxsTmFtZSI6IlRob21hcyBUaGVsZW4iLCJpc3N1ZWRBdCI6IjIwMjAtMDctMTZUMDI6NTk6MTQuOTQwKzAwOjAwIiwiY29uc3VtZXJLZXkiOiJ0aGVjb25zdW1lcmtleSIsImV4cCI6MTU5NDkzMzE1NCwidXNlcklkIjoiaHR0cDpcL1wvb3JjaWQub3JnXC8wMDAwLTAwMDItMTc1Ni0yMTI4IiwidHRsIjo2NDgwMCwiaWF0IjoxNTk0ODY4MzU0fQ.KRw1gqwgwpxoQuss6Mwc-9rnoC6Dur1NgJkOpRX4YW-C3ko67QvQinp5nO38Lvzwixy2AExn0eypJ8ktK_jMofY9F-WbTDTQGxw9qzFcdg8M-xLwcvA3YnGJFI9iQVv7F2ux2hOAdqPo486X5prTYUZXCLyB7XBUi6j1BpQ9cIg91us2OoVCF1UEKpeqoecA8YF-Tr-_nbYjKTDhyF5W2E_6uyVrmC3XCe75alXCWn3Pnb0x1v2TJcIgqq8zu-RpwsbWCHfs8_fi2_6Lrf9RSmpl3f_YHpMY_FudJHqMBQR1Y-ilcQIlGrTgWUxxZ9BigZH1sOtPo4rU3k1wXplsyA
  < Charset: utf-8
  < Connection: close
  < Content-Length: 1366
  < Content-Type: multipart/form-data; boundary=5748d4b5c1f2461ab19387522f7b5531
  < Host: dev.nceas.ucsb.edu
  < POST /knb/d1/mn/v2/object HTTP/1.1
  < User-Agent: safari
  
  
  
  << Request body is not a string-like type >>
  > HTTP/1.1 400 400
  > Date: Thu, 16 Jul 2020 02:59:54 GMT
  > Server: Apache/2.4.29 (Ubuntu)
  > X-Frame-Options: SAMEORIGIN
  > X-Frame-Options: sameorigin
  > Vary: User-Agent,Authorization
  > Content-Length: 326
  > Access-Control-Allow-Origin: 
  > Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
  > Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
  > Access-Control-Allow-Credentials: true
  > Connection: close
  > Content-Type: text/xml
  > 
  <?xml version="1.0" encoding="UTF-8"?><error detailCode="1180" errorCode="400" name="InvalidSystemMetadata">
      <description>The checksum calculated from the saved local file is 1CBFC1B80D09EB3B413D79D533DBA28B. But it doesn't match the value from the system metadata 1e5789ec516201cad7bc9e742cb81d58.</description>
  </error>
identifier: <unset>
nodeId: <unset>

[2020-07-16 02:59:55,296: CRITICAL/MainProcess] Unrecoverable error: UsageError('Unable to reconstruct instance of absent namespace',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/dist-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 302, in on_result_readable
    next(it)
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 283, in _recv_message
    message = load(bufv)
  File "/usr/local/lib/python3.5/dist-packages/pyxb/namespace/__init__.py", line 718, in __new__
    raise pyxb.UsageError('Unable to reconstruct instance of absent namespace')
pyxb.exceptions_.UsageError: Unable to reconstruct instance of absent namespace
[2020-07-16 02:59:56,077: ERROR/MainProcess] Error on stopping Pool: RuntimeError('_SimpleQueue objects should only be shared between processes through inheritance',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/dist-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 302, in on_result_readable
    next(it)
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 283, in _recv_message
    message = load(bufv)
  File "/usr/local/lib/python3.5/dist-packages/pyxb/namespace/__init__.py", line 718, in __new__
    raise pyxb.UsageError('Unable to reconstruct instance of absent namespace')
pyxb.exceptions_.UsageError: Unable to reconstruct instance of absent namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 373, in stop
    return self.obj.stop()
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/base.py", line 122, in stop
    self.on_stop()
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/prefork.py", line 140, in on_stop
    self._pool.join()
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 1578, in join
    stop_if_not_current(self._result_handler)
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 143, in stop_if_not_current
    thread.stop(timeout)
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 500, in stop
    self.on_stop_not_started()
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 332, in on_stop_not_started
    check_timeouts()
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 744, in handle_event
    next(self._it)
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 697, in handle_timeouts
    cache = copy.deepcopy(self.cache)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
  File "/usr/local/lib/python3.5/dist-packages/billiard/queues.py", line 348, in __getstate__
    context.assert_spawning(self)
  File "/usr/local/lib/python3.5/dist-packages/billiard/context.py", line 421, in assert_spawning
    ' through inheritance' % type(obj).__name__
RuntimeError: _SimpleQueue objects should only be shared between processes through inheritance
```

**Comment by ThomasThelen** [comment]
The crashing  _may_ have something to do with [this](https://github.com/celery/billiard/issues/260) issue. We're running
celery==4.2.1
billiard==3.5.0.5

From the issue,
"Celery still depends on the buggy version as of today (celery 4.2.1 -> billiard<3.6.0,>=3.5.0.2)"

I'll go ahead and update these in girder_wholetale and see if anything breaks-ideally this issue isn't reproduced.

**Comment by ThomasThelen** [comment]
I believe this is fixed with the python upgrade. Closing.
