### ISSUE TITLE
Publishing to DataONE shouldn't crash celery_worker

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/gwvolman#67]
Publishing from my dev instance crashes celery worker.
```
core@willis8-dev-large ~/deploy-dev $ docker logs -f celery_worker
/usr/local/lib/python3.5/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2019-04-11 20:23:48,876: INFO/MainProcess] Connected to redis://redis:6379//
[2019-04-11 20:23:48,885: INFO/MainProcess] mingle: searching for neighbors
[2019-04-11 20:23:49,902: INFO/MainProcess] mingle: all alone
[2019-04-11 20:23:49,914: INFO/MainProcess] celery@o6z4a0kziuxn35p7q2yo5e3n8 ready.
[2019-04-11 20:25:51,203: INFO/MainProcess] Received task: gwvolman.tasks.publish[e6e7ea28-62c2-4385-86ea-d8d0cb46d339]
/usr/local/lib/python3.5/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2019-04-11 20:25:51,824: WARNING/ForkPoolWorker-1] Instances with absent namespaces can only be reconstructed in-session
[2019-04-11 20:25:51,853: ERROR/ForkPoolWorker-1] <class 'int'>
[2019-04-11 20:25:51,855: ERROR/ForkPoolWorker-1] <class 'pyxb.binding.datatypes.string'>
[2019-04-11 20:25:51,855: ERROR/ForkPoolWorker-1] <class 'pyxb.binding.datatypes.string'>
[2019-04-11 20:25:51,856: ERROR/ForkPoolWorker-1] <class 'str'>
[2019-04-11 20:25:51,856: ERROR/ForkPoolWorker-1] <class 'NoneType'>
[2019-04-11 20:25:51,856: ERROR/ForkPoolWorker-1] <class 'NoneType'>
[2019-04-11 20:25:51,856: ERROR/ForkPoolWorker-1] InvalidToken(errorCode="401", detailCode="2190", description="Session is required to generate an Identifier at this Node.", traceInformation="< Accept-Encoding: gzip, deflate
< Accept: */*
< Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi02MTQ4LTcxOTYiLCJmdWxsTmFtZSI6IkNyYWlnIFdpbGxpcyIsImlzc3VlZEF0IjoiMjAxOS0wNC0xMVQyMDoyNTo1MC45OTgrMDA6MDAiLCJjb25zdW1lcktleSI6InRoZWNvbnN1bWVya2V5IiwiZXhwIjoxNTU1MDc5MTUwLCJ1c2VySWQiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi02MTQ4LTcxOTYiLCJ0dGwiOjY0ODAwLCJpYXQiOjE1NTUwMTQzNTB9.bwv-nfnMbUC1a4vEXoaSadJWbz3g8uxmScn0UAIZAW9S7uVYaWhzgQkHhDAf9mkK-sAUvGeeYn6GeIcqA56xc1pUqeVlR_JKEuSkUP7zzk_VnaGzlhszmecYv9pWH216ub9A9_yKZjAWfkhlwLuNJsSRhADk4oX-vO1rHUXjr2IUYfWTvvsoUlHykvdfLc4mN2UpyR-D60fBu0Puf74eZSN-JUtdpZ_4WVAnnIb1VkZ2GLliCi4kLuuHF40B0HaQEO-YMKMtuZ5CKJ6_OdvOSEJjRo4r-Q9OlNrQ5QLG24X1p6dgTvbN_GQ1F79WJeABZ6hzj1yWkFJ3ari3e6Cydg
< Charset: utf-8
< Connection: close
< Content-Length: 129
< Content-Type: multipart/form-data; boundary=aa428bcdabbf45c88bbe65b80a817918
< Host: dev.nceas.ucsb.edu
< POST /knb/d1/mn/v2/generate HTTP/1.1
< User-Agent: safari



<< Request body is not a string-like type >>
> HTTP/1.1 401 Unauthorized
> Date: Thu, 11 Apr 2019 20:25:51 GMT
> Server: Apache/2.4.7 (Ubuntu)
> X-Frame-Options: SAMEORIGIN
> X-Frame-Options: sameorigin
> Vary: User-Agent,Authorization
> Set-Cookie: JSESSIONID=A51C56DA2C14895137DF255EC7954005; Path=/knb/; Secure
> Content-Length: 200
> Access-Control-Allow-Origin:
> Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
> Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
> Access-Control-Allow-Credentials: true
> Connection: close
> Content-Type: text/xml
>
<?xml version="1.0" encoding="UTF-8"?><error detailCode="2190" errorCode="401" name="InvalidToken">
    <description>Session is required to generate an Identifier at this Node.</description>
</error>", identifier="None", nodeId="None")
[2019-04-11 20:25:51,857: ERROR/ForkPoolWorker-1] Task gwvolman.tasks.publish[e6e7ea28-62c2-4385-86ea-d8d0cb46d339] raised unexpected: InvalidToken(errorCode="401", detailCode="2190", description="Session is required to generate an Identifier at this Node.", traceInformation="< Accept-Encoding: gzip, deflate
< Accept: */*
< Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi02MTQ4LTcxOTYiLCJmdWxsTmFtZSI6IkNyYWlnIFdpbGxpcyIsImlzc3VlZEF0IjoiMjAxOS0wNC0xMVQyMDoyNTo1MC45OTgrMDA6MDAiLCJjb25zdW1lcktleSI6InRoZWNvbnN1bWVya2V5IiwiZXhwIjoxNTU1MDc5MTUwLCJ1c2VySWQiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi02MTQ4LTcxOTYiLCJ0dGwiOjY0ODAwLCJpYXQiOjE1NTUwMTQzNTB9.bwv-nfnMbUC1a4vEXoaSadJWbz3g8uxmScn0UAIZAW9S7uVYaWhzgQkHhDAf9mkK-sAUvGeeYn6GeIcqA56xc1pUqeVlR_JKEuSkUP7zzk_VnaGzlhszmecYv9pWH216ub9A9_yKZjAWfkhlwLuNJsSRhADk4oX-vO1rHUXjr2IUYfWTvvsoUlHykvdfLc4mN2UpyR-D60fBu0Puf74eZSN-JUtdpZ_4WVAnnIb1VkZ2GLliCi4kLuuHF40B0HaQEO-YMKMtuZ5CKJ6_OdvOSEJjRo4r-Q9OlNrQ5QLG24X1p6dgTvbN_GQ1F79WJeABZ6hzj1yWkFJ3ari3e6Cydg
< Charset: utf-8
< Connection: close
< Content-Length: 129
< Content-Type: multipart/form-data; boundary=aa428bcdabbf45c88bbe65b80a817918
< Host: dev.nceas.ucsb.edu
< POST /knb/d1/mn/v2/generate HTTP/1.1
< User-Agent: safari



<< Request body is not a string-like type >>
> HTTP/1.1 401 Unauthorized
> Date: Thu, 11 Apr 2019 20:25:51 GMT
> Server: Apache/2.4.7 (Ubuntu)
> X-Frame-Options: SAMEORIGIN
> X-Frame-Options: sameorigin
> Vary: User-Agent,Authorization
> Set-Cookie: JSESSIONID=A51C56DA2C14895137DF255EC7954005; Path=/knb/; Secure
> Content-Length: 200
> Access-Control-Allow-Origin:
> Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
> Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
> Access-Control-Allow-Credentials: true
> Connection: close
> Content-Type: text/xml
>
<?xml version="1.0" encoding="UTF-8"?><error detailCode="2190" errorCode="401" name="InvalidToken">
    <description>Session is required to generate an Identifier at this Node.</description>
</error>", identifier="None", nodeId="None")
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 410, in publish
    self.job_manager
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 132, in publish
    eml_pid = client.generateIdentifier(scheme="UUID").value()
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 527, in generateIdentifier
    return self._read_dataone_type_response(response, 'Identifier')
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 261, in _read_dataone_type_response
    self._raise_exception(response)
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 219, in _raise_exception
    self._raise_dataone_exception(response)
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 184, in _raise_dataone_exception
    raise d1_exception
d1_common.types.exceptions.InvalidToken: name: InvalidToken
errorCode: 401
detailCode: 2190
description: Session is required to generate an Identifier at this Node.
traceInformation:
  < Accept-Encoding: gzip, deflate
  < Accept: */*
  < Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi02MTQ4LTcxOTYiLCJmdWxsTmFtZSI6IkNyYWlnIFdpbGxpcyIsImlzc3VlZEF0IjoiMjAxOS0wNC0xMVQyMDoyNTo1MC45OTgrMDA6MDAiLCJjb25zdW1lcktleSI6InRoZWNvbnN1bWVya2V5IiwiZXhwIjoxNTU1MDc5MTUwLCJ1c2VySWQiOiJodHRwOlwvXC9vcmNpZC5vcmdcLzAwMDAtMDAwMi02MTQ4LTcxOTYiLCJ0dGwiOjY0ODAwLCJpYXQiOjE1NTUwMTQzNTB9.bwv-nfnMbUC1a4vEXoaSadJWbz3g8uxmScn0UAIZAW9S7uVYaWhzgQkHhDAf9mkK-sAUvGeeYn6GeIcqA56xc1pUqeVlR_JKEuSkUP7zzk_VnaGzlhszmecYv9pWH216ub9A9_yKZjAWfkhlwLuNJsSRhADk4oX-vO1rHUXjr2IUYfWTvvsoUlHykvdfLc4mN2UpyR-D60fBu0Puf74eZSN-JUtdpZ_4WVAnnIb1VkZ2GLliCi4kLuuHF40B0HaQEO-YMKMtuZ5CKJ6_OdvOSEJjRo4r-Q9OlNrQ5QLG24X1p6dgTvbN_GQ1F79WJeABZ6hzj1yWkFJ3ari3e6Cydg
  < Charset: utf-8
  < Connection: close
  < Content-Length: 129
  < Content-Type: multipart/form-data; boundary=aa428bcdabbf45c88bbe65b80a817918
  < Host: dev.nceas.ucsb.edu
  < POST /knb/d1/mn/v2/generate HTTP/1.1
  < User-Agent: safari



  << Request body is not a string-like type >>
  > HTTP/1.1 401 Unauthorized
  > Date: Thu, 11 Apr 2019 20:25:51 GMT
  > Server: Apache/2.4.7 (Ubuntu)
  > X-Frame-Options: SAMEORIGIN
  > X-Frame-Options: sameorigin
  > Vary: User-Agent,Authorization
  > Set-Cookie: JSESSIONID=A51C56DA2C14895137DF255EC7954005; Path=/knb/; Secure
  > Content-Length: 200
  > Access-Control-Allow-Origin:
  > Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
  > Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
  > Access-Control-Allow-Credentials: true
  > Connection: close
  > Content-Type: text/xml
  >
  <?xml version="1.0" encoding="UTF-8"?><error detailCode="2190" errorCode="401" name="InvalidToken">
      <description>Session is required to generate an Identifier at this Node.</description>
  </error>
identifier: <unset>
nodeId: <unset>

[2019-04-11 20:25:51,869: CRITICAL/MainProcess] Unrecoverable error: UsageError('Unable to reconstruct instance of absent namespace',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/dist-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 302, in on_result_readable
    next(it)
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 283, in _recv_message
    message = load(bufv)
  File "/usr/local/lib/python3.5/dist-packages/pyxb/namespace/__init__.py", line 718, in __new__
    raise pyxb.UsageError('Unable to reconstruct instance of absent namespace')
pyxb.exceptions_.UsageError: Unable to reconstruct instance of absent namespace
[2019-04-11 20:25:51,875: ERROR/MainProcess] Error on stopping Pool: TypeError("can't pickle memoryview objects",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/dist-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 302, in on_result_readable
    next(it)
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 283, in _recv_message
    message = load(bufv)
  File "/usr/local/lib/python3.5/dist-packages/pyxb/namespace/__init__.py", line 718, in __new__
    raise pyxb.UsageError('Unable to reconstruct instance of absent namespace')
pyxb.exceptions_.UsageError: Unable to reconstruct instance of absent namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 373, in stop
    return self.obj.stop()
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/base.py", line 122, in stop
    self.on_stop()
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/prefork.py", line 140, in on_stop
    self._pool.join()
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 1578, in join
    stop_if_not_current(self._result_handler)
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 143, in stop_if_not_current
    thread.stop(timeout)
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 500, in stop
    self.on_stop_not_started()
  File "/usr/local/lib/python3.5/dist-packages/celery/concurrency/asynpool.py", line 332, in on_stop_not_started
    check_timeouts()
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 744, in handle_event
    next(self._it)
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 697, in handle_timeouts
    cache = copy.deepcopy(self.cache)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.5/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: can't pickle memoryview objects

 -------------- celery@o6z4a0kziuxn35p7q2yo5e3n8 v4.2.1 (windowlicker)
---- **** -----
--- * ***  * -- Linux-4.19.34-coreos-x86_64-with-Ubuntu-16.04-xenial 2019-04-11 20:23:48
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         girder_worker:0x7f2443c6f160
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                .> manager          exchange=manager(direct) key=manager
                .> o6z4a0kziuxn35p7q2yo5e3n8 exchange=o6z4a0kziuxn35p7q2yo5e3n8(direct) key=o6z4a0kziuxn35p7q2yo5e3n8

[tasks]
  . girder_worker.docker.tasks.docker_run
  . gwvolman.tasks.build_tale_image
  . gwvolman.tasks.create_volume
  . gwvolman.tasks.import_tale
  . gwvolman.tasks.launch_container
  . gwvolman.tasks.publish
  . gwvolman.tasks.remove_volume
  . gwvolman.tasks.shutdown_container
  . gwvolman.tasks.update_container
```

**Comment by ThomasThelen** [comment]
Here's another stack trace of an exception that crashes gwvolman


```
User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2019-09-04 16:09:24,741: INFO/MainProcess] Connected to redis://redis:6379//
[2019-09-04 16:09:24,758: INFO/MainProcess] mingle: searching for neighbors
[2019-09-04 16:09:25,798: INFO/MainProcess] mingle: all alone
[2019-09-04 16:09:25,810: INFO/MainProcess] celery@ir78gppb213fizvyhgp0nt7gd ready.
[2019-09-04 16:10:14,648: INFO/MainProcess] Received task: gwvolman.tasks.publish[8a3ff152-28c6-45a3-b1f9-a51aa742652b]
/usr/local/lib/python3.5/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2019-09-04 16:10:34,104: WARNING/ForkPoolWorker-4] Obsoleting urn:uuid:420b377a-55e1-44b7-ba77-5e0820502a46
[2019-09-04 16:10:34,612: WARNING/ForkPoolWorker-4] Error. Should rollback... Failed to obsolete package. InvalidRequest
[2019-09-04 16:10:34,656: ERROR/ForkPoolWorker-4] Task gwvolman.tasks.publish[8a3ff152-28c6-45a3-b1f9-a51aa742652b] raised unexpected: ValueError('Failed to obsolete package. InvalidRequest',)
Traceback (most recent call last):
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 67, in obsolete
    client.update(old_pid, resource_map, new_pid, sysmeta)
  File "/usr/local/lib/python3.5/dist-packages/d1_client/mnclient.py", line 137, in update
    return self._read_dataone_type_response(response, 'Identifier')
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 261, in _read_dataone_type_response
    self._raise_exception(response)
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 219, in _raise_exception
    self._raise_dataone_exception(response)
  File "/usr/local/lib/python3.5/dist-packages/d1_client/baseclient.py", line 184, in _raise_dataone_exception
    raise d1_exception
d1_common.types.exceptions.InvalidRequest: name: InvalidRequest
errorCode: 400
detailCode: 1202
description: The object with the provided identifier was not found.
traceInformation:
  < Accept-Encoding: gzip, deflate
  < Accept: */*
  < Authorization: Bearer <MY_TOKEN>
  < Charset: utf-8
  < Connection: close
  < Content-Length: 13366
  < Content-Type: multipart/form-data; boundary=0714bbf73e6e4322ae0aa9646213d667
  < Host: dev.nceas.ucsb.edu
  < PUT /knb/d1/mn/v2/object/urn:uuid:420b377a-55e1-44b7-ba77-5e0820502a46 HTTP/1.1
  < User-Agent: safari



  << Request body is not a string-like type >>
  > HTTP/1.1 400 400
  > Date: Wed, 04 Sep 2019 16:11:53 GMT
  > Server: Apache/2.4.29 (Ubuntu)
  > X-Frame-Options: SAMEORIGIN
  > X-Frame-Options: sameorigin
  > Vary: User-Agent,Authorization
  > Content-Length: 197
  > Access-Control-Allow-Origin:
  > Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
  > Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
  > Access-Control-Allow-Credentials: true
  > Connection: close
  > Content-Type: text/xml
  >
  <?xml version="1.0" encoding="UTF-8"?><error detailCode="1202" errorCode="400" name="InvalidRequest">
      <description>The object with the provided identifier was not found.</description>
  </error>
identifier: <unset>
nodeId: <unset>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 497, in publish
    self.job_manager
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 246, in publish
    res_meta)
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 69, in obsolete
    raise ValueError('Failed to obsolete package. {}'.format(e.__class__.__name__))
ValueError: Failed to obsolete package. InvalidRequest
```

**Comment by ThomasThelen** [comment]
I believe this is fixed with the python upgrade. Closing.
